"""Generate per-page ``_revisions.md`` change-history partials from git.

Every "owned" page — initiative / epic / item READMEs, weekly-update
decks, and SOPs — closes with an auto-generated change-history table:
the page's front-matter ``owner`` plus the git commits that touched the
page's scope (date, author, subject). Pages include it via
``{{< include _revisions.md >}}`` (or ``_revisions-<stem>.md`` for
SOPs/chapters, which share a directory).

Scopes (so child churn doesn't spam parent tables):

- item README       → its item directory, recursive
- epic README       → epic dir MINUS experiments/ features/ issues/
- initiative README → initiative dir MINUS epics/
- WU deck           → its WU directory
- SOP / chapter qmd → that single file

Semantics: **committed history only** — the table is one render behind
an uncommitted edit, by design (working-tree state would make renders
non-reproducible mid-edit). The satellite cache interplay is automatic:
a new commit changes this partial's bytes → that page's cache key
changes → it re-renders exactly once. No git state in the cache key.

Limitation: no ``--follow``, so renaming an item/epic directory (gantt
reprioritization) restarts its visible table — same trade-off the repo
already accepts for IDs-in-dir-names. The footer points at
``git log --follow`` for the full story.

Runs as a pre-render hook (after build_file_trees.py). Degrades to a
stub partial when git is unavailable so the render never fails. All
writes go through write-only-if-changed (cache-stable).
"""

from __future__ import annotations

import sys
from pathlib import Path

from _lib import (
    ROOT,
    git_file_history,
    read_front_matter,
    write_text_if_changed,
)

MAX_ROWS = 15

# Map raw git author names to display names (handy when one human
# commits under more than one identity, or to give agents a name).
# Add entries as needed, e.g. {"jdoe123": "Jane Doe"}.
AUTHOR_DISPLAY = {}

HEADER = ("<!-- Auto-generated by scripts/render/build_revisions.py.\n"
          "     Do not edit by hand — re-run the script or "
          "`quarto render`. -->\n")


def _md_escape(text: str) -> str:
    return str(text).replace("|", "\\|")


def owned_pages():
    """Yield (page_qmd, partial_path, scope) triples.

    ``scope`` is (include_prefix, exclude_prefixes) of repo-relative
    posix paths, or ("FILE", page_rel) for single-file pages.
    """
    initiatives = ROOT / "initiatives"
    if initiatives.exists():
        for init in sorted(p for p in initiatives.iterdir()
                           if p.is_dir() and not p.name.startswith("_")):
            init_rel = init.relative_to(ROOT).as_posix()
            readme = init / "README.qmd"
            if readme.exists():
                yield (readme, init / "_revisions.md",
                       (init_rel + "/", (init_rel + "/epics/",)))
            epics_dir = init / "epics"
            if not epics_dir.exists():
                continue
            for epic in sorted(p for p in epics_dir.iterdir() if p.is_dir()):
                epic_rel = epic.relative_to(ROOT).as_posix()
                e_readme = epic / "README.qmd"
                if e_readme.exists():
                    excludes = tuple(f"{epic_rel}/{kind}/" for kind in
                                     ("experiments", "features", "issues"))
                    yield (e_readme, epic / "_revisions.md",
                           (epic_rel + "/", excludes))
                for kind in ("experiments", "features", "issues"):
                    kind_dir = epic / kind
                    if not kind_dir.exists():
                        continue
                    for item in sorted(p for p in kind_dir.iterdir()
                                       if p.is_dir()):
                        i_readme = item / "README.qmd"
                        if not i_readme.exists():
                            continue
                        item_rel = item.relative_to(ROOT).as_posix()
                        yield (i_readme, item / "_revisions.md",
                               (item_rel + "/", ()))

    updates = ROOT / "updates"
    if updates.exists():
        for qmd in sorted(updates.glob("WU-*/index.qmd")):
            wu_rel = qmd.parent.relative_to(ROOT).as_posix()
            yield (qmd, qmd.parent / "_revisions.md", (wu_rel + "/", ()))

    # Chapters/SOPs share a directory, so each page gets its own
    # `_revisions-<stem>.md`. Generated only for pages that actually
    # include one (opt-in as chapters grow prose); the SOPs all do.
    chapters = ROOT / "chapters"
    if chapters.exists():
        for qmd in sorted(chapters.rglob("*.qmd")):
            if qmd.name.startswith("_"):
                continue
            partial = qmd.parent / f"_revisions-{qmd.stem}.md"
            try:
                text = qmd.read_text(encoding="utf-8")
            except OSError:
                continue
            if partial.name in text:
                rel = qmd.relative_to(ROOT).as_posix()
                yield (qmd, partial, ("FILE", rel))


def commits_for_scope(history: dict, scope) -> list:
    include, exclude = scope
    if include == "FILE":
        commits = list(history.get(exclude, []))
    else:
        seen: set[str] = set()
        commits = []
        for path, path_commits in history.items():
            if not path.startswith(include):
                continue
            if any(path.startswith(x) for x in exclude):
                continue
            for c in path_commits:
                if c.sha not in seen:
                    seen.add(c.sha)
                    commits.append(c)
    # Newest first. Date strings are ISO so they sort lexically; sha
    # tiebreak keeps the output deterministic within a day.
    commits.sort(key=lambda c: (c.date, c.sha), reverse=True)
    return commits


def render_partial(page: Path, commits: list, scope) -> str:
    fm = read_front_matter(page)
    owner = fm.get("owner") or "unassigned"
    include, exclude = scope
    log_path = exclude if include == "FILE" else include.rstrip("/")

    lines = [HEADER, "## Change history", "",
             f"**Owner:** {_md_escape(owner)}", ""]
    if not commits:
        lines += ["_No committed history yet._", ""]
    else:
        lines += ["| Date | Author | Change |", "|---|---|---|"]
        for c in commits[:MAX_ROWS]:
            author = AUTHOR_DISPLAY.get(c.author, c.author)
            lines.append(f"| {c.date} | {_md_escape(author)} | "
                         f"{_md_escape(c.subject)} |")
        lines.append("")
        if len(commits) > MAX_ROWS:
            lines += [f"_Showing {MAX_ROWS} of {len(commits)} commits — "
                      f"full history: `git log --follow -- {log_path}`_", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    history = git_file_history()
    if not history:
        print("revisions: git history unavailable — writing stub partials",
              file=sys.stderr)
    written = total = 0
    for page, partial, scope in owned_pages():
        total += 1
        commits = commits_for_scope(history, scope) if history else []
        if write_text_if_changed(partial, render_partial(page, commits,
                                                         scope)):
            written += 1
            print(f"  wrote {partial.relative_to(ROOT)}")
    if written == 0:
        print(f"revisions: all {total} partials unchanged")
    else:
        print(f"revisions: {written}/{total} partial(s) regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
