"""Generate the dashboard board partial (``_board.md`` at repo root).

Three sections, all derived from front matter + git (never hand-edit):

1. **Epic status tables** — one per initiative, in gantt-section order.
   Replaces the hand-maintained tables that used to live in
   ``index.qmd`` (whose raw ``.qmd`` hrefs leaked into the published
   site); links are emitted directly as ``…/README.html``.
2. **Item kanban** — open / in-progress / blocked / done columns, one
   card per item (id, title, gantt badge, owner). Styled by the
   ``.kanban`` rules in ``styles/thesis.scss``.
3. **Stale items** — ``in-progress`` items whose directory has no
   commit in the last ``--stale-weeks`` weeks (default 3). Linear-style
   nudge against zombie work. Items with no committed history yet
   (freshly scaffolded) count as fresh.

``index.qmd`` consumes the partial via ``{{< include _board.md >}}``.
Runs as a pre-render hook after build_revisions.py. Output is
write-only-if-changed and shows absolute last-activity dates (never
"N days ago") so the bytes only change when reality changes.
"""

from __future__ import annotations

import argparse
import html
import sys
from datetime import date, timedelta
from pathlib import Path

from _lib import (
    ROOT,
    git_file_history,
    read_front_matter,
    write_text_if_changed,
)

INITIATIVES = ROOT / "initiatives"
OUT = ROOT / "_board.md"
ITEM_KINDS = ("experiments", "features", "issues")
COLUMNS = ("open", "in-progress", "blocked", "done")
COLUMN_TITLES = {"open": "Open", "in-progress": "In progress",
                 "blocked": "Blocked", "done": "Done"}
DEFAULT_STALE_WEEKS = 3

HEADER = ("<!-- Auto-generated by scripts/render/build_board.py.\n"
          "     Do not edit by hand — re-run the script or "
          "`quarto render`. -->\n")


def _md_escape(text: str) -> str:
    return str(text).replace("|", "\\|")


def collect() -> tuple[list[dict], list[dict]]:
    """Return (initiatives, items) read from front matter."""
    initiatives: list[dict] = []
    items: list[dict] = []
    if not INITIATIVES.exists():
        return initiatives, items
    for init in sorted(p for p in INITIATIVES.iterdir()
                       if p.is_dir() and not p.name.startswith("_")):
        ifm = read_front_matter(init / "README.qmd")
        if not ifm.get("title"):
            continue
        epics: list[dict] = []
        epics_dir = init / "epics"
        if epics_dir.exists():
            for epic in sorted(p for p in epics_dir.iterdir() if p.is_dir()):
                efm = read_front_matter(epic / "README.qmd")
                if not efm.get("title"):
                    continue
                epics.append({
                    "title": efm["title"],
                    "gantt_id": str(efm.get("gantt-id", "")),
                    "status": efm.get("status", ""),
                    "owner": efm.get("owner", ""),
                    "href": f"initiatives/{init.name}/epics/{epic.name}/README.html",
                })
                for kind in ITEM_KINDS:
                    kind_dir = epic / kind
                    if not kind_dir.exists():
                        continue
                    for item in sorted(p for p in kind_dir.iterdir()
                                       if p.is_dir()):
                        fm = read_front_matter(item / "README.qmd")
                        if not fm.get("title"):
                            continue
                        items.append({
                            "id": fm.get("item-id", item.name),
                            "title": fm["title"],
                            "gantt_id": str(fm.get("gantt-id", "")),
                            "status": fm.get("status", "open"),
                            "owner": fm.get("owner", ""),
                            "rel": item.relative_to(ROOT).as_posix(),
                            "href": (f"initiatives/{init.name}/epics/"
                                     f"{epic.name}/{kind}/{item.name}/"
                                     f"README.html"),
                        })
        initiatives.append({
            "title": ifm["title"],
            "section": str(ifm.get("gantt-section", "")),
            "epics": epics,
        })
    initiatives.sort(key=lambda i: i["section"])
    return initiatives, items


def last_activity(items: list[dict]) -> None:
    """Annotate each item with its newest commit date (or None)."""
    history = git_file_history()
    latest: dict[str, str] = {}
    for path, commits in history.items():
        for it in items:
            prefix = it["rel"] + "/"
            if path.startswith(prefix) or path == it["rel"] + "/README.qmd":
                newest = max(c.date for c in commits)
                if it["rel"] not in latest or newest > latest[it["rel"]]:
                    latest[it["rel"]] = newest
    for it in items:
        it["last_activity"] = latest.get(it["rel"])


def epic_tables(initiatives: list[dict]) -> list[str]:
    lines: list[str] = []
    for init in initiatives:
        lines.append(f"### {init['section']} — {init['title']}")
        lines.append("")
        if not init["epics"]:
            lines += ["_No epics yet._", ""]
            continue
        lines.append("| Gantt | Epic | Status | Owner |")
        lines.append("|---|---|---|---|")
        for e in init["epics"]:
            link = f"[{_md_escape(e['title'])}]({e['href']})"
            lines.append(f"| {e['gantt_id']} | {link} | {e['status']} | "
                         f"{_md_escape(e['owner'])} |")
        lines.append("")
    return lines


def kanban(items: list[dict], stale_cutoff: date) -> list[str]:
    # column-body-outset: a little wider than the prose column for the
    # board, but margin-aware so it never slides under the sidebar/TOC
    # (plain column-page overlapped them). The grid itself is responsive
    # (see .kanban in styles/thesis.scss).
    lines = ["## Item board", "", '::: {.column-body-outset}',
             '<div class="kanban">']
    for status in COLUMNS:
        cards = [i for i in items if i["status"] == status]
        # Anything non-canonical surfaces in Open so it can't hide.
        if status == "open":
            cards += [i for i in items if i["status"] not in COLUMNS]
        cards.sort(key=lambda i: i["id"])
        lines.append('<div class="kanban-col">')
        lines.append(f"<h4>{COLUMN_TITLES[status]} "
                     f"<span class='kanban-count'>{len(cards)}</span></h4>")
        for c in cards:
            stale = _is_stale(c, stale_cutoff)
            classes = "kanban-card kanban-stale" if stale else "kanban-card"
            lines.append(f'<div class="{classes}">')
            lines.append(f'<a href="{c["href"]}">{html.escape(c["id"])}</a>')
            lines.append(f'<div class="kanban-title">'
                         f'{html.escape(c["title"])}</div>')
            meta = " · ".join(x for x in (c["gantt_id"],
                                          html.escape(c["owner"])) if x)
            lines.append(f'<div class="kanban-meta">{meta}</div>')
            if stale:
                lines.append(f'<div class="kanban-stale-note">stale — last '
                             f'activity {c["last_activity"]}</div>')
            lines.append("</div>")
        lines.append("</div>")
    lines += ["</div>", ":::", ""]
    return lines


def _is_stale(item: dict, cutoff: date) -> bool:
    if item["status"] != "in-progress":
        return False
    last = item.get("last_activity")
    if last is None:
        return False  # never committed → freshly scaffolded, not zombie
    return date.fromisoformat(last) < cutoff


def stale_section(items: list[dict], cutoff: date, weeks: int) -> list[str]:
    stale = sorted((i for i in items if _is_stale(i, cutoff)),
                   key=lambda i: i["last_activity"])
    lines = ["### Stale items", "",
             f"_`in-progress` items with no commit in {weeks}+ weeks._", ""]
    if not stale:
        lines += ["_None — every in-progress item has recent activity._", ""]
        return lines
    for i in stale:
        lines.append(f"- [{i['id']}]({i['href']}) — last activity "
                     f"{i['last_activity']} ({_md_escape(i['owner'])})")
    lines.append("")
    return lines


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate _board.md.")
    ap.add_argument("--stale-weeks", type=int, default=DEFAULT_STALE_WEEKS,
                    help=f"weeks without a commit before an in-progress "
                         f"item is flagged stale (default "
                         f"{DEFAULT_STALE_WEEKS})")
    args = ap.parse_args(argv)

    initiatives, items = collect()
    last_activity(items)
    cutoff = date.today() - timedelta(weeks=args.stale_weeks)

    lines = [HEADER]
    lines += epic_tables(initiatives)
    lines += kanban(items, cutoff)
    lines += stale_section(items, cutoff, args.stale_weeks)
    text = "\n".join(lines).rstrip() + "\n"
    if write_text_if_changed(OUT, text):
        print(f"board: wrote {OUT.relative_to(ROOT)} "
              f"({len(items)} items, {len(initiatives)} initiatives)")
    else:
        print("board: unchanged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
